# Generated by Django 3.0.8 on 2020-07-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srt', models.FileField(blank=True, upload_to='')),
                ('movie', models.FileField(blank=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
